SELECT ROUND(long_w, 4)
FROM station
WHERE (ROUND(LAT_N, 4)) > 38.7780
ORDER BY LAT_N ASC
LIMIT 1
;


-- or

SELECT ROUND(LONG_W, 4)
FROM STATION
GROUP BY LONG_W
HAVING ROUND(MIN(LAT_N), 4) > 38.7780
ORDER BY ROUND(MIN(LAT_N), 4) ASC
LIMIT 1;